# API service and deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
spec:
  replicas: 3 # tells the service to run 3 pods with this deployment
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
        - name: api-demo
          image: sergeysedelnikovstoraenso/kubernetes-demo-api:1.0.1
          resources:
            requests:
              cpu: 70m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80
          env:
            - name: 'NODE_ENV'
              value: 'production'
            - name: PORT
              value: '80'
---
apiVersion: v1
kind: Service
metadata:
  name: api-demo
  labels:
    name: api-demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: api-demo